spring:
   profiles: 
     active: 
     -dev
---
spring:
   profiles: dev
   application:
    name:  microsericers-config-3344-dev
---
spring:
   profiles: test
   application:
    name:  microsericers-config-3344-test